module OctNov
  module Models
    type user_delete_params = {  } & OctNov::Internal::Type::request_parameters

    class UserDeleteParams < OctNov::Internal::Type::BaseModel
      extend OctNov::Internal::Type::RequestParameters::Converter
      include OctNov::Internal::Type::RequestParameters

      def initialize: (?request_options: OctNov::request_opts) -> void

      def to_hash: -> { request_options: OctNov::RequestOptions }
    end
  end
end
