module OctNov
  module Resources
    class Pets
      def create: (
        name: String,
        photo_urls: ::Array[String],
        ?id: Integer,
        ?category: OctNov::Category,
        ?status: OctNov::Models::Pet::status,
        ?tags: ::Array[OctNov::Pet::Tag],
        ?request_options: OctNov::request_opts
      ) -> OctNov::Pet

      def retrieve: (
        Integer pet_id,
        ?request_options: OctNov::request_opts
      ) -> OctNov::Pet

      def update: (
        name: String,
        photo_urls: ::Array[String],
        ?id: Integer,
        ?category: OctNov::Category,
        ?status: OctNov::Models::Pet::status,
        ?tags: ::Array[OctNov::Pet::Tag],
        ?request_options: OctNov::request_opts
      ) -> OctNov::Pet

      def delete: (
        Integer pet_id,
        ?request_options: OctNov::request_opts
      ) -> nil

      def find_by_status: (
        ?status: OctNov::Models::PetFindByStatusParams::status,
        ?request_options: OctNov::request_opts
      ) -> OctNov::Models::pet_find_by_status_response

      def find_by_tags: (
        ?tags: ::Array[String],
        ?request_options: OctNov::request_opts
      ) -> OctNov::Models::pet_find_by_tags_response

      def update_by_id: (
        Integer pet_id,
        ?name: String,
        ?status: String,
        ?request_options: OctNov::request_opts
      ) -> nil

      def upload_image: (
        Integer pet_id,
        image: OctNov::Internal::file_input,
        ?additional_metadata: String,
        ?request_options: OctNov::request_opts
      ) -> OctNov::Models::PetUploadImageResponse

      def initialize: (client: OctNov::Client) -> void
    end
  end
end
